{"uuid":"ac43fac9-b0d0-4615-8740-3b60b1201048","historyId":"44c4b034264ad7ed8e98c4d14f81f62","fullName":"com.tester.ex03_Selenium_Locators.TestSelenium_13_Mini_Project2_TagName.vwo_free_trail_error_verify","labels":[{"name":"package","value":"com.tester.ex03_Selenium_Locators.TestSelenium_13_Mini_Project2_TagName"},{"name":"testClass","value":"com.tester.ex03_Selenium_Locators.TestSelenium_13_Mini_Project2_TagName"},{"name":"testMethod","value":"vwo_free_trail_error_verify"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"LearningSeleniumATB13x"},{"name":"subSuite","value":"com.tester.ex03_Selenium_Locators.TestSelenium_13_Mini_Project2_TagName"},{"name":"host","value":"KASAM"},{"name":"thread","value":"17800@KASAM.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"owner","value":"Kajal"},{"name":"severity","value":"blocker"}],"links":[{"name":"https://bugz.atlassian.net/browse/BUG-17","type":"tms"}],"name":"vwo_free_trail_error_verify","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [true] but found [false]","trace":"java.lang.AssertionError: expected [true] but found [false]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1590)\r\n\tat org.testng.Assert.assertTrue(Assert.java:57)\r\n\tat org.testng.Assert.assertTrue(Assert.java:67)\r\n\tat com.tester.ex03_Selenium_Locators.TestSelenium_13_Mini_Project2_TagName.vwo_free_trail_error_verify(TestSelenium_13_Mini_Project2_TagName.java:27)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:741)\r\n\tat org.testng.TestRunner.run(TestRunner.java:616)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","description":"Verify that the error message comes with invalid email on signup page.","steps":[],"attachments":[],"parameters":[],"start":1756479187941,"stop":1756479200528}